### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [13]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [10]:
print(car.dtype,mpg.dtype,origin.dtype,origin.dtype)

object float64 object object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

I am not entirely sure what this action is called, assigning a value or abbreviation or designation. 

This is done to make it easier to code as you only have to type np instead of numpy. 

np is a common value to asign numpy to, you can assign numpy to any value/str but np is convention and makes you code easier to read.

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [127]:
#format with the the key value method from the book

print(car.ndim,mpg.ndim,origin.ndim,horsepower.ndim)

#same method for all arrays, just '.ndim'

1 1 1 1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [128]:
horsepower.sum()
horsepower.min()
horsepower.max()
horsepower.mean()
np.median(horsepower)

#format this

print(horsepower.sum(),horsepower.min(), horsepower.mean(), np.median(horsepower))

42033.0 0.0 103.5295566502463 93.5


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [21]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [3]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

print(select_more[:,-1])

[3 6 9]


6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [129]:
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [130]:
np.log(mpg)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13864\67066281.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [161]:
US_cars = np.array(df['Origin'] == 'US')
US_cars

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [162]:
car[US_cars]

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [160]:
Europe_index = (df[df['Origin'] == 'Europe'])

Europe_index['Horsepower'].median()

76.0

10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [97]:
Japan_index = (df[df['Origin'] == 'Japan'])
US_index = (df[df['Origin'] == 'US'])

US_eff = US_index['MPG'].median()
Japan_eff = Japan_index['MPG'].median()

if US_eff > Japan_eff:
    print('US cars are more fuel efficient on avearage than Japanese cars')
else:
    print('Japanese cars are on average more efficient than US cars')

Japanese cars are on average more efficient than US cars


11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [164]:
# correlation coefficient it looks like is the slope off the scatter plot graph

MPG_to_Weight = df[['MPG','Weight']]
print(MPG_to_Weight.corr())

#im sure there is a way to clean this function up, as to only display the relevant value.

#the relationship of MPG to Weight is negative meaning that as one increases, the other decreases. As well, the correlation coeeficient is almost -1,
#Meaning the relationship is almost directly inverse.

            MPG   Weight
MPG     1.00000 -0.78751
Weight -0.78751  1.00000


Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

In [148]:
#I know this solution is quite clunky and I'm sure there is a much simpler way of achieving the same thing

US_index =pd.DataFrame(df[df['Origin'] == 'US'])
Japan_index =pd.DataFrame(df[df['Origin'] == 'Japan'])
Europe_index =pd.DataFrame(df[df['Origin'] == 'Europe'])


average_by_country = pd.DataFrame([[US_index['Weight'].median(),Japan_index['Weight'].median(),Europe_index['Weight'].median()],
                                 [US_index['MPG'].median(),Japan_index['MPG'].median(),Europe_index['MPG'].median()],
                                  [US_index['Horsepower'].median(),Japan_index['Horsepower'].median(),Europe_index['Horsepower'].median()]],
                                 ['Weight','MPG','Horsepower'],columns=['US','Japan','Europe'])
average_by_country

US   Japan  Europe
Weight      3380.50  2155.0  2246.0
MPG           18.35    31.6    26.0
Horsepower   105.00    75.0    76.0